### ISSUE TITLE
PvP Broken in WG region

### ISSUE THREAD

**Issue by VeganFN** [MajekDev/PvPToggle#34]
**Describe the bug**
I am having issues with PvPing in WorldGuard regions.
[Spawn(Arena)] Arena Priority is 1,000, Spawn is 1. Players enter spawn where PvP is on deny, the enter Arena where PvP is allow, but cannot PvP because when executing command /pvptoggle  players get the message You are in a region with pvp forced on. That's good. The arena is supposed to force pvp on. However, when players go to pvp, they cannot. When checking their PvPToggle status, it is still toggled off.

**To Reproduce**
N/A (will provide more info if needed)

**Expected behavior**
Players will automatically be set to PvP on and can PvP

**Screenshots**
N/A (will provide more info if needed)

**Software (please complete the following information):**
 - Server Implementation: Paper 1.18 Experimental Build #52
 - Minecraft Version 1.17.1 (Playable 1.7.x - 1.18.x)
 - Java Version 17
 - Plugin Version 3.0.2

**Additional context**
N/A

A note from me: It could be due to not having a hook between PvPToggle and WG. If this is the issue, could you help me through the steps as I have never used hooks before. If the issue is something else, I will help to figure this out as much as I can.

**Comment by Majekdor** [comment]
Fixed in latest update in my testing.
